/* ═══════════════════════════════════════════════════════════
   CASE STUDY DATA — Project portfolio content
   ═══════════════════════════════════════════════════════════ */

var CS_DATA = {
  nativecamp: {
    label:    '01 — Professional Project',
    title:    'NativeCamp Platform',
    color:    '#1a56db',
    meta: [
      { key: 'Role',      val: 'Backend Developer' },
      { key: 'Company',   val: 'Forty Degree Celcius, Inc.' },
      { key: 'Duration',  val: 'Jun 2024 – Present' },
      { key: 'Team Size', val: '5–10 Engineers' },
    ],
    overview: 'NativeCamp is a large-scale Japanese online English conversation platform with millions of users. As a backend developer at Forty Degree Celcius, Inc., I joined the maintenance and feature development team responsible for platform stability and new capabilities.',
    challenge: 'The main challenges included working within a large existing codebase using CakePHP and Angular, understanding complex business logic around lesson scheduling and user roles, and delivering bug fixes without disrupting active users.',
    contributions: [
      'Developed and integrated new feature modules into the existing CakePHP backend',
      'Implemented and extended role-based access control for different user tiers',
      'Investigated and resolved production bugs reported by QA and end users',
      'Collaborated with frontend engineers to align API contracts with Angular components',
      'Participated in code reviews and team standups in an Agile workflow',
    ],
    outcome: 'Maintained high platform reliability with zero critical downtime during my involvement. Delivered feature increments on schedule across multiple sprint cycles.',
    tags: ['CakePHP', 'Angular', 'jQuery', 'JavaScript', 'HTML/CSS', 'MySQL', 'REST API'],
    github: 'javascript:void(0)', // No public repo for this project
    live:   'https://nativecamp.net/',
    svgBg:  '#eef3ff', svgAc: '#1a56db', svgType: 'dashboard',
  },

  workwisehr: {
    label:    '02 — Internship Project',
    title:    'WorkwiseHR — HR Information System',
    color:    '#16a34a',
    meta: [
      { key: 'Role',      val: 'Full-Stack Developer' },
      { key: 'Company',   val: 'Onsource, Inc.' },
      { key: 'Duration',  val: '3 Months (Internship)' },
      { key: 'Team Size', val: 'Solo + Supervisor' },
    ],
    overview: 'WorkwiseHR is a comprehensive HR information system developed during my internship at Onsource, Inc. The system automates core HR processes including employee records, attendance tracking, leave management, and payroll computation.',
    challenge: 'Designing a system from scratch that could handle real payroll logic, complex leave policies, and secure multi-role access — while working solo under a tight internship timeline.',
    contributions: [
      'Architected the full system from database schema to frontend UI',
      'Built RESTful APIs using Laravel for all HR modules',
      'Implemented JWT-based authentication with role-based permissions (HR Admin, Employee, Manager)',
      'Optimised MySQL queries for payroll computation involving multiple deduction rules',
      'Designed a React.js frontend with role-conditional views and dashboards',
    ],
    outcome: 'Delivered a fully functional HR system within the internship period. Received commendation from the supervising engineer for code quality and system architecture.',
    tags: ['Laravel', 'React.js', 'MySQL', 'REST API', 'JWT', 'PHP'],
    github: 'javascript:void(0)',
    live:   'https://workwise-hr-front-end.vercel.app/login',
    svgBg:  '#f0fdf4', svgAc: '#16a34a', svgType: 'hrm',
  },

  iot: {
    label:    '03 — Thesis Project',
    title:    'IoT Pet Feeding System',
    color:    '#d97706',
    meta: [
      { key: 'Role',      val: 'Full-Stack + IoT Dev' },
      { key: 'Context',   val: 'Undergraduate Thesis' },
      { key: 'Duration',  val: '6 Months' },
      { key: 'Team Size', val: '4 Members' },
    ],
    overview: 'A thesis project combining a Next.js web app, React Native mobile app, and IoT hardware to create an automated pet feeding system. Pet owners can set customised feeding schedules and monitor their pets remotely via real-time Firebase communication.',
    challenge: 'Synchronising real-time state between hardware, a web app, and a mobile app — ensuring commands sent from any platform were reliably received and executed by the physical device.',
    contributions: [
      'Led frontend development for both the Next.js web dashboard and React Native mobile app',
      'Integrated Firebase Realtime Database for instant bi-directional communication with IoT hardware',
      'Designed the feeding schedule data model to support flexible time-based triggers',
      'Implemented push notifications for feeding confirmations and low-food alerts',
      'Coordinated with hardware team members to define the data contract between app and device',
    ],
    outcome: 'Thesis received a passing grade with distinction. The system successfully demonstrated reliable remote feeding control with under 2-second latency between app command and device execution.',
    tags: ['Next.js', 'React Native', 'Firebase', 'IoT', 'Realtime DB', 'Push Notifications'],
    github: 'javascript:void(0)',
    live:   null,
    svgBg:  '#fefce8', svgAc: '#d97706', svgType: 'iot',
  },

  animist: {
    label:    '04 — Mobile App',
    title:    'Animist Anime Streaming App',
    color:    '#9333ea',
    meta: [
      { key: 'Role',      val: 'Mobile Developer' },
      { key: 'Context',   val: 'Personal Project' },
      { key: 'Platform',  val: 'iOS & Android' },
      { key: 'Stack',     val: 'React Native' },
    ],
    overview: 'Animist is a personal mobile project — a cross-platform anime streaming application built with React Native. It integrates third-party anime content APIs to provide users with browsing, searching, and streaming capabilities in a clean mobile UI.',
    challenge: 'Handling paginated API responses efficiently, implementing smooth video player behaviour on both iOS and Android, and managing a favourites list that persisted across sessions without a backend.',
    contributions: [
      'Built a full React Native app from scratch targeting both iOS and Android',
      'Integrated third-party anime REST APIs for content discovery and episode streaming',
      'Implemented search with debounced queries to avoid excessive API calls',
      'Built category browsing with horizontal scroll carousels and lazy image loading',
      'Implemented AsyncStorage-based favourites with offline persistence',
    ],
    outcome: 'A polished personal project that demonstrates cross-platform mobile development competency, API integration skills, and attention to mobile UX patterns.',
    tags: ['React Native', 'AsyncStorage', 'REST API', 'NoSQL', 'iOS', 'Android'],
    github: 'javascript:void(0)',
    live:   null,
    svgBg:  '#fdf2f8', svgAc: '#9333ea', svgType: 'mobile',
  },

  inventory: {
    label:    '05 — Inventory System',
    title:    'Computer Parts Inventory System',
    color:    '#ea580c',
    meta: [
      { key: 'Role',      val: 'Full-Stack Developer' },
      { key: 'Context',   val: 'Academic Project' },
      { key: 'Duration',  val: '2 Months' },
      { key: 'Stack',     val: 'PHP + MySQL' },
    ],
    overview: 'A web-based inventory management system for tracking computer hardware components. Built to streamline stock monitoring, purchasing records, and low-stock reporting for a simulated computer shop environment.',
    challenge: 'Designing a clean, fast interface for non-technical users while keeping the backend data model flexible enough to handle variable component attributes (RAM type, SSD vs HDD, etc.).',
    contributions: [
      'Designed the MySQL database schema for flexible product categorisation',
      'Built CRUD operations for inventory items with image upload support',
      'Implemented real-time stock level indicators with low-stock visual alerts',
      'Created a dashboard with summary charts for stock value and turnover',
      'Added jQuery-powered search and sort on the inventory table without page reload',
    ],
    outcome: 'Delivered a functional inventory system that earned a high academic score. Demonstrated clean MVC structure and practical database design.',
    tags: ['PHP', 'JavaScript', 'jQuery', 'MySQL', 'Bootstrap', 'AJAX'],
    github: 'javascript:void(0)',
    live:   null,
    svgBg:  '#fff7ed', svgAc: '#ea580c', svgType: 'inventory',
  },

  aar9speed: {
    label:    '06 — Sales System',
    title:    'AAR9SPEED Sales & Inventory System',
    color:    '#0284c7',
    meta: [
      { key: 'Role',      val: 'Full-Stack Developer' },
      { key: 'Client',    val: 'Motor Parts Business' },
      { key: 'Duration',  val: '2 Months' },
      { key: 'Stack',     val: 'PHP + MySQL' },
    ],
    overview: 'A combined sales and inventory management system built for AAR9SPEED, a motor parts retailer. The system handles day-to-day sales transactions, inventory tracking, supplier management, and generates business reports.',
    challenge: 'Designing a POS-style sales flow that non-technical staff could use quickly, while keeping accurate inventory counts that deducted on each sale and flagged reorder points.',
    contributions: [
      'Built a POS-style sales interface for fast transaction entry',
      'Implemented automatic inventory deduction on each confirmed sale',
      'Created a supplier and purchase order module for restocking workflows',
      'Developed sales and inventory reports exportable to printable format',
      'Added low-stock alert system with configurable reorder thresholds',
    ],
    outcome: 'Deployed and used by the client for daily operations. Reduced manual stock counting effort and provided the owner with clear daily sales visibility.',
    tags: ['PHP', 'JavaScript', 'jQuery', 'MySQL', 'Bootstrap', 'AJAX', 'FPDF'],
    github: 'javascript:void(0)',
    live:   null,
    svgBg:  '#f0f9ff', svgAc: '#0284c7', svgType: 'sales',
  },
};
